shell = "zsh"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
use = ["powerlevel10k.zsh-theme"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
